version: '2'

networks:
  idus:

services:
  mysql:
    image: library/mysql:5.7.31
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: idus
      MYSQL_USER: idus
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - idus

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - './source:/var/www/html'
    networks:
      - idus

  api:
    build:
      context: ./docker/nginx
    container_name: api
    ports:
      - '8080:80'
    volumes:
      - './source:/var/www/html'
    depends_on:
      - php
      - mysql
    networks:
      - idus

  composer:
    build:
      context: ./docker/compose
    container_name: composer
    volumes:
      - "./source:/var/www/html"
    working_dir: "/var/www/html"
    depends_on:
      - php
    user: idus
    networks:
      - idus
    entrypoint: ['composer', '--no-scripts', '--ignore-platform-reqs']

  artisan:
    build:
      context: ./docker/php
    container_name: artisan
    volumes:
      - ./source:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: idus
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - idus